name: Build and Publish

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.1.33
      - name: Install dependencies
        run: bun install --no-update
      - name: Build
        run: |
          bun build
          cat package.json | jq ".version = \"$(echo "${{ github.ref_name }}" | sed 's/^v//')"\" > package.json
      - name: Publish
        run: |
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          bun publish --access public
